### DISCUSSION TITLE
Change CHANGELOG Strategy

### DISCUSSION THREAD

**Discussion by DrDBanner** [Intermesh/groupoffice#1240] [Ideas]
Hi,

at the moment the CHANGELOG strategy seems a bit hard to follow if you want to see what happened during all the updates. Please consider a change in strategy to releasenotes. Seems way more handy to follow. Keep up the good work!

 <img width="580" alt="Bildschirmfoto 2025-03-18 um 15 37 03" src="https://github.com/user-attachments/assets/7c2582fd-3343-49a7-9889-5da65a4777fc" />

> I have done a [search for similar discussions](https://github.com/Intermesh/groupoffice/discussions?discussions_q=Change+CHANGELOG+Strategy)*

erm .. nope

**Comment by DrDBanner** [comment]
@mschering 
File: .github/workflows/release-notes.yml
### HowTo
- The workflow is automatically triggered when a tag starting with v* (e.g., v1.2.3) is pushed.
- It extracts the latest changes from CHANGELOG.md.
- A new GitHub Release is created with these extracted changes as the release notes.
```
name: Generate Release Notes

on:
  push:
    tags:
      - "v*"

jobs:
  update-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Changelog Entry
        id: changelog
        run: |
          awk '/^## \[/{flag=1; next} /^## /{flag=0} flag' CHANGELOG.md > latest_changes.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: latest_changes.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
### Alternative run block

```
- name: Generate Release Notes File
  run: |
    echo "## 🚀 New Release: ${{ github.ref_name }}" > release_notes.txt
    echo "" >> release_notes.txt
    echo "### What's New?" >> release_notes.txt
    echo "" >> release_notes.txt
    awk '/^## \[/{flag=1; next} /^## /{flag=0} flag' CHANGELOG.md >> release_notes.txt
    echo "" >> release_notes.txt
    echo "Thanks for using our project! 🙌" >> release_notes.txt

```
