### ISSUE TITLE
Mail sent from GO renders with very large font size

### ISSUE THREAD

**Issue by KevoSoftworks** [Intermesh/groupoffice#1075]
Whenever I send a mail from Group Office to a recipient that uses the Microsoft Outlook web client, the font size for the recipient is very large. Text within reply elements become even larger, with overlap of text if the mail is long enough. See the image below for an example.
![image](https://github.com/Intermesh/groupoffice/assets/4387878/d18a9572-5f2e-4129-af6e-f6f4b0918710)

The problem stems from the styling that is sent by GO, see here an excerpt from the mail source:

```css
body, p, span, div {
  font-family: Helvetica, Arial, sans-serif;
  font-size: 1.6rem;
  color: var(--fg-text);
  font-weight: normal;
  line-height: 2.4rem;
  background-color: white;
}
```

From this, if the mail is rendered using a HTML viewer, the font size of regular text is 1.6 times larger than any other normal text.

This was observed with v6.8.10.
